import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

test('reviews enforce checked rosters, independent scores, privacy, resumability and attendance gating',async()=>{
 const db=new PGlite();
 try {
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public,storage to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to authenticated;
 create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;`);
 const dir=new URL('../supabase/migrations/',import.meta.url);
 for(const file of readdirSync(dir).filter(f=>f.endsWith('.sql')).sort()) await db.exec(readFileSync(new URL(file,dir),'utf8'));
 const [admin,a,b,c,outsider]=[1,2,3,4,5].map(n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`);
 for(const [i,id] of [admin,a,b,c,outsider].entries())await db.exec(`insert into auth.users values('${id}','test${i}@example.com','{"display_name":"Player ${i}"}');`);
 await db.exec(`update public.profiles set role='admin' where id='${admin}';update public.profiles set membership='monthly';`);
 const game='00000000-0000-0000-0000-000000000010',next='00000000-0000-0000-0000-000000000011';
 await db.exec(`insert into public.sessions(id,name,played_on,starts_at,created_by) values('${game}','Review test',current_date,now()-interval '3 hours','${admin}'),('${next}','Next game',current_date,now()+interval '3 days','${admin}');
 insert into public.attendances(session_id,player_id,status) values('${game}','${a}','confirmed'),('${game}','${b}','confirmed'),('${game}','${c}','confirmed'),('${game}','${outsider}','waiting');`);
 async function asUser(id:string,sql:string){await db.exec(`begin;set local role authenticated;set local "request.jwt.claim.sub"='${id}';`);try{const result=await db.query<Record<string,unknown>>(sql);await db.exec('commit');return result;}catch(e){await db.exec('rollback');throw e;}}
 const pending=async(id:string)=>(await asUser(id,'select public.pending_player_reviews() as p')).rows[0].p as {targets:{id:string}[];total:number}[];
 assert.deepEqual(await pending(a),[]);
 await assert.rejects(asUser(a,`select public.start_player_reviews('${game}',array['${a}','${b}']::uuid[])`),/administrador/);
 await assert.rejects(asUser(admin,`select public.start_player_reviews('${game}',array['${a}','${outsider}']::uuid[])`),/confirmados/);
 await assert.rejects(asUser(admin,`select public.start_player_reviews('${game}',array['${a}','${a}']::uuid[])`),/distintos/);
 await assert.rejects(asUser(admin,`select public.start_player_reviews('${next}',array['${a}','${b}']::uuid[])`),/começado/);
 await asUser(admin,`select public.start_player_reviews('${game}',array['${a}','${b}','${c}']::uuid[])`);
 assert.equal((await pending(a))[0].targets.length,2);
 assert.deepEqual(await pending(outsider),[]);
 await assert.rejects(asUser(admin,`select public.start_player_reviews('${game}',array['${a}','${b}']::uuid[])`),/já foram/);
 await assert.rejects(asUser(a,`select public.set_attendance_manual('${next}',true)`),/Conclua a avaliação/);
 await asUser(outsider,`select public.set_attendance_manual('${next}',true)`);
 await assert.rejects(asUser(a,`select public.submit_player_review('${game}','${a}',5,5)`),/não permitida/);
 await assert.rejects(asUser(outsider,`select public.submit_player_review('${game}','${a}',5,5)`),/não permitida/);
 await assert.rejects(asUser(a,`select public.submit_player_review('${game}','${b}',6,5)`),/entre 1 e 5/);
 await asUser(a,`select public.submit_player_review('${game}','${b}',4,null)`);
 await asUser(a,`select public.submit_player_review('${game}','${b}',5,null)`);
 assert.equal((await pending(a))[0].targets.length,1);
 assert.equal((await asUser(a,'select * from public.player_reviews')).rows.length,1);
 assert.equal((await asUser(b,'select * from public.player_reviews')).rows.length,0);
 assert.equal((await asUser(admin,'select * from public.player_reviews')).rows.length,0);
 assert.equal((await asUser(a,`select * from public.player_review_results('${game}')`)).rows.length,0);
 await assert.rejects(asUser(a,`insert into public.player_reviews values('${game}','${b}','${c}',5,5,now())`));
 await assert.rejects(asUser(a,`update public.review_participants set waived_at=now()`));
 await assert.rejects(asUser(a,`select public.manage_player_reviews('${game}','waive','${b}')`),/administrador/);
 await asUser(a,`select public.submit_player_review('${game}','${c}',null,3)`);
 assert.deepEqual(await pending(a),[]);
 await asUser(a,`select public.set_attendance_manual('${next}',true)`);
 await asUser(b,`select public.manage_player_reviews('${game}','help')`);
 assert.equal((await asUser(admin,`select help_requested from public.review_participants where player_id='${b}'`)).rows[0].help_requested,true);
 await asUser(admin,`select public.manage_player_reviews('${game}','waive','${b}')`);
 assert.deepEqual(await pending(b),[]);
 await asUser(c,`select public.submit_player_review('${game}','${a}',null,null)`);
 await asUser(c,`select public.submit_player_review('${game}','${b}',3,4)`);
 assert.deepEqual(await pending(c),[]);
 const results=(await asUser(a,`select * from public.player_review_results('${game}') order by player_id`)).rows;
 assert.deepEqual(results.map(r=>[r.player_id,Number(r.attack),Number(r.attack_count),Number(r.defense),Number(r.defense_count)]),[[a,0,0,0,0],[b,4,2,4,1],[c,0,0,3,1]]);
 await assert.rejects(asUser(a,`select public.submit_player_review('${game}','${b}',1,1)`),/encerrada/);
 await db.exec('begin;set local role anon;');await assert.rejects(db.query('select public.pending_player_reviews()'));await db.exec('rollback');
 await asUser(admin,`select public.delete_closed_session('${game}')`);
 assert.equal((await db.query('select * from public.review_rounds')).rows.length,0);
 assert.equal((await db.query('select * from public.player_reviews')).rows.length,0);
 }finally{await db.close();}
});
