import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

test('PostgreSQL permissions, closed games, capacity and audit survive direct API-equivalent queries',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public,storage to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;
 grant select,insert,update,delete on storage.objects to authenticated;
 create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;`);
 await db.exec(readFileSync(new URL('../supabase/migrations/001_pelada_club.sql',import.meta.url),'utf8'));
 await db.exec(readFileSync(new URL('../supabase/migrations/002_capacity_per_session.sql',import.meta.url),'utf8'));
 const admin='00000000-0000-0000-0000-000000000001',a='00000000-0000-0000-0000-000000000002',b='00000000-0000-0000-0000-000000000003';
 await db.exec(`insert into public.roster_slots(email,display_name,role) values('admin@example.com','Admin','admin'),('a@example.com','Player A','player'),('b@example.com','Player B','player');
 insert into auth.users(id,email) values('${admin}','admin@example.com'),('${a}','a@example.com'),('${b}','b@example.com');`);
 await assert.rejects(db.exec(`insert into auth.users values(gen_random_uuid(),'outsider@example.com')`),/Cadastro restrito/);
 await db.exec(readFileSync(new URL('../supabase/migrations/003_open_signup.sql',import.meta.url),'utf8'));
 await db.exec(readFileSync(new URL('../supabase/migrations/003_open_signup.sql',import.meta.url),'utf8'));
 const outsider='00000000-0000-0000-0002-000000000001';
 await db.exec(`insert into auth.users(id,email,raw_user_meta_data) values('${outsider}','outsider@example.com','{"display_name":"  Convidado  ","role":"admin"}')`);
 assert.deepEqual((await db.query(`select display_name,role from public.profiles where id='${outsider}'`)).rows,[{display_name:'Convidado',role:'player'}]);
 assert.deepEqual((await db.query(`select role from public.profiles where id='${admin}'`)).rows,[{role:'admin'}]);
 const match='00000000-0000-0000-0000-000000000010';
 async function asUser(id:string,sql:string){await db.exec(`begin;set local role authenticated;set local "request.jwt.claim.sub"='${id}';`);try{const result=await db.query(sql);await db.exec('commit');return result;}catch(e){await db.exec('rollback');throw e;}}
 await asUser(admin,`insert into public.sessions(id,name,played_on,created_by) values('${match}','Pelada teste','2026-01-01','${admin}')`);
 await assert.rejects(asUser(outsider,`insert into public.sessions(name,played_on,created_by) values('Hack','2026-01-01','${outsider}')`));
 await assert.rejects(asUser(a,`insert into public.sessions(name,played_on,created_by) values('Hack','2026-01-01','${a}')`));
 await assert.rejects(asUser(a,`update public.profiles set role='admin' where id='${a}'`));
 await asUser(a,`update public.profiles set display_name='Jogador A' where id='${a}'`);
 const untouched=await asUser(a,`update public.profiles set display_name='Hack' where id='${b}' returning id`);assert.equal(untouched.rows.length,0);
 await asUser(a,`insert into public.performances(session_id,player_id,goals,assists) values('${match}','${a}',2,3)`);
 await assert.rejects(asUser(b,`insert into public.performances(session_id,player_id,goals) values('${match}','${a}',50)`));
 const denied=await asUser(b,`update public.performances set goals=99 where player_id='${a}' returning id`);assert.equal(denied.rows.length,0);
 await assert.rejects(asUser(a,`update public.performances set goals=-1 where player_id='${a}'`));
 await assert.rejects(asUser(a,`update public.performances set goals=100 where player_id='${a}'`));
 await assert.rejects(asUser(a,`insert into public.performances(session_id,player_id) values('${match}','${a}')`),/unique/);
 await asUser(a,`update public.performances set goals=3 where player_id='${a}' and revision=1`);
 const stale=await asUser(a,`update public.performances set goals=4 where player_id='${a}' and revision=1 returning id`);assert.equal(stale.rows.length,0);
 await asUser(admin,`update public.sessions set status='closed' where id='${match}'`);
 await assert.rejects(asUser(a,`update public.performances set goals=6 where player_id='${a}'`),/não está aberta/);
 await asUser(admin,`update public.performances set assists=5 where player_id='${a}'`);
 const audit=await asUser(admin,'select * from public.audit_log order by id');assert.equal(audit.rows.length,3);assert.equal((audit.rows[2] as {actor_id:string}).actor_id,admin);
 assert.equal((await asUser(a,'select * from public.audit_log')).rows.length,0);
 await assert.rejects(asUser(a,`delete from public.audit_log`));
 await assert.rejects(asUser(a,`insert into public.roster_slots values('new@example.com','Hacker','admin',now())`));
 await assert.rejects(asUser(admin,`insert into public.roster_slots(email,display_name,role) values('admin2@example.com','Admin 2','admin')`));
 await asUser(a,`insert into storage.objects(bucket_id,name) values('player-photos','${a}/photo.webp')`);
 await assert.rejects(asUser(b,`insert into storage.objects(bucket_id,name) values('player-photos','${a}/hack.webp')`));
 const photos=await asUser(b,`delete from storage.objects where name='${a}/photo.webp' returning id`);assert.equal(photos.rows.length,0);
 await assert.rejects(asUser(a,`update public.profiles set photo_path='${b}/photo.webp' where id='${a}'`));
 await db.exec(`begin;set local role anon;`);await assert.rejects(db.query('select * from public.performances'));await db.exec('rollback');
 await asUser(admin,`insert into public.roster_slots(email,display_name) select 'player'||n||'@example.com','Player '||n from generate_series(4,30) n`);
 await db.exec(`insert into auth.users(id,email) select ('00000000-0000-0000-0001-'||lpad(n::text,12,'0'))::uuid,'player'||n||'@example.com' from generate_series(4,30) n`);
 assert.equal((await asUser(admin,'select * from public.profiles')).rows.length,31);
 await asUser(admin,`update public.sessions set status='open' where id='${match}'`);
 await asUser(admin,`insert into public.performances(session_id,player_id) select '${match}',id from public.profiles where id<>'${a}' order by id limit 23`);
 assert.equal((await asUser(admin,`select * from public.performances where session_id='${match}'`)).rows.length,24);
 const guest='00000000-0000-0000-0001-000000000030';
 await assert.rejects(asUser(guest,`insert into public.performances(session_id,player_id) values('${match}','${guest}')`),/24 participantes/);
 await assert.rejects(asUser(admin,`insert into public.performances(session_id,player_id) values('${match}','${guest}')`),/24 participantes/);
 await asUser(a,`update public.performances set goals=4 where session_id='${match}' and player_id='${a}'`);
 const another='00000000-0000-0000-0000-000000000011';
 await asUser(admin,`insert into public.sessions(id,name,played_on,created_by) values('${another}','Outra pelada','2026-01-02','${admin}')`);
 await asUser(guest,`insert into public.performances(session_id,player_id,goals) values('${another}','${guest}',2)`);
 assert.equal((await asUser(guest,`select * from public.performances where session_id='${another}'`)).rows.length,1);

 // Upgrade live-style data: old games retain their original participants and scores.
 await db.exec(readFileSync(new URL('../supabase/migrations/004_attendance.sql',import.meta.url),'utf8'));
 await db.exec(readFileSync(new URL('../supabase/migrations/005_joao_pessoa_timezone.sql',import.meta.url),'utf8'));
 await db.exec(readFileSync(new URL('../supabase/migrations/005_joao_pessoa_timezone.sql',import.meta.url),'utf8'));
 assert.equal((await asUser(a,'select * from public.attendances')).rows.length,25);
 await asUser(a,`update public.performances set assists=6 where session_id='${match}' and player_id='${a}'`);
 const upcoming='00000000-0000-0000-0000-000000000012';
 await asUser(admin,`insert into public.sessions(id,name,played_on,starts_at,created_by) values('${upcoming}','Próxima','2000-01-01',clock_timestamp()+interval '2 hours','${admin}')`);
 assert.equal((await db.query<{ok:boolean}>(`select played_on=(starts_at at time zone 'America/Fortaleza')::date as ok from public.sessions where id='${upcoming}'`)).rows[0].ok,true);
 await assert.rejects(asUser(admin,`insert into public.sessions(name,played_on,created_by) values('Sem hora','2026-01-01','${admin}')`),/data e o horário/);
 await asUser(a,`select public.set_attendance('${upcoming}',true)`);
 await asUser(a,`select public.set_attendance('${upcoming}',true)`);
 assert.equal((await asUser(a,`select * from public.attendances where session_id='${upcoming}'`)).rows.length,1);
 await assert.rejects(asUser(a,`insert into public.performances(session_id,player_id) values('${upcoming}','${a}')`),/não está aberta/);
 await assert.rejects(asUser(a,`insert into public.attendances(session_id,player_id) values('${upcoming}','${b}')`));
 await assert.rejects(asUser(a,`delete from public.attendances where session_id='${upcoming}'`));
 await asUser(a,`select public.set_attendance('${upcoming}',false)`);
 const members=(await db.query<{id:string}>('select id from public.profiles order by id limit 24')).rows;
 for(const member of members)await asUser(member.id,`select public.set_attendance('${upcoming}',true)`);
 await assert.rejects(asUser(outsider,`select public.set_attendance('${upcoming}',true)`),/24 participantes/);
 await asUser(a,`select public.set_attendance('${upcoming}',false)`);
 await asUser(outsider,`select public.set_attendance('${upcoming}',true)`);
 assert.equal((await asUser(a,`select * from public.attendances where session_id='${upcoming}'`)).rows.length,24);
 await asUser(admin,`update public.sessions set starts_at=clock_timestamp()+interval '1 hour 10 seconds' where id='${upcoming}'`);
 await asUser(outsider,`select public.set_attendance('${upcoming}',false)`);
 await asUser(admin,`update public.sessions set starts_at=clock_timestamp()+interval '59 minutes' where id='${upcoming}'`);
 await assert.rejects(asUser(b,`select public.set_attendance('${upcoming}',false)`),/cancelamento encerrou/);
 await asUser(outsider,`select public.set_attendance('${upcoming}',true)`);
 await assert.rejects(asUser(outsider,`select public.set_attendance('${upcoming}',false)`),/cancelamento encerrou/);
 await asUser(admin,`update public.sessions set starts_at=clock_timestamp()-interval '1 minute' where id='${upcoming}'`);
 await assert.rejects(asUser(a,`select public.set_attendance('${upcoming}',true)`),/confirmações encerraram/);
 await assert.rejects(asUser(a,`insert into public.performances(session_id,player_id) values('${upcoming}','${a}')`),/Confirme sua presença/);
 await asUser(b,`insert into public.performances(session_id,player_id,goals) values('${upcoming}','${b}',2)`);
 await asUser(admin,`update public.sessions set status='closed' where id='${upcoming}'`);
 await assert.rejects(asUser(b,`update public.performances set goals=5 where session_id='${upcoming}' and player_id='${b}'`),/não está aberta/);
 await asUser(admin,`update public.performances set goals=3 where session_id='${upcoming}' and player_id='${b}'`);
 await assert.rejects(asUser(b,`select public.set_attendance('${upcoming}',false)`),/encerrada/);
 await assert.rejects(asUser('00000000-0000-0000-0000-000000000099',`select public.set_attendance('${upcoming}',true)`),/não autorizado/);
 await db.exec('begin;set local role anon;');await assert.rejects(db.query(`select public.set_attendance('${upcoming}',true)`));await db.exec('rollback');
 await db.close();
});
