'use client';
import {useEffect,useState} from 'react';
import {attendanceWindow,currentDate,dateLabel,scheduleLabel,type Match,type Performance,type Profile} from '@/lib/model';
import {friendlyError} from '@/lib/supabase';

export function MatchRow({match,performance,onClick,isAdmin,participants,confirmed,onAttendance}:{participants:Profile[];confirmed:boolean;match:Match;performance?:Performance;onClick:()=>void;isAdmin:boolean;onAttendance:(confirm:boolean)=>Promise<void>}){
 const [now,setNow]=useState(Date.now()),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const window=attendanceWindow(match,now),full=participants.length>=24;
 const available=confirmed&&(isAdmin&&Boolean(performance)||(match.status==='open'&&(window.started||(!match.starts_at&&Boolean(performance)&&match.played_on<=currentDate()))));
 async function change(confirm:boolean){setBusy(true);setError('');try{await onAttendance(confirm);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 return <article className="attendance-card"><div className="match-row"><div className="match-date"><strong>{match.played_on.slice(8)}</strong><span>{dateLabel(match.played_on).split(' ').slice(1).join(' ')}</span></div><div className="match-info"><h3>{match.name}</h3><p>{match.starts_at?scheduleLabel(match.starts_at)+' · Brasília':'Horário a definir pelo organizador'}</p><span className={`status ${match.status}`}>{match.status==='closed'?'Encerrada':window.started?'Em andamento':confirmed?'Sua presença está confirmada':'Confirme sua presença'}</span><span className="muted"> · {participants.length}/24 confirmados</span></div><div className="attendance-actions">{confirmed?<button className="secondary" disabled={busy||!window.canCancel||Boolean(performance)} onClick={()=>change(false)}>{busy?'Salvando…':'Cancelar presença'}</button>:<button className="primary" disabled={busy||!window.canConfirm||full} onClick={()=>change(true)}>{busy?'Salvando…':full?'Lotada':'Confirmar presença'}</button>}<button className="secondary" disabled={!available||busy} onClick={onClick}>{performance?'Editar total':'Registrar desempenho'}</button></div></div><div className="attendance-details">{match.starts_at&&<p className="muted">Cancelamento até {scheduleLabel(new Date(Date.parse(match.starts_at)-3600000).toISOString())}. {window.canConfirm&&!window.canCancel?'Ao confirmar agora, não será possível cancelar.':''}</p>}{performance&&<p>{performance.goals} gols · {performance.assists} assistências</p>}{error&&<p className="error" role="alert">{error}</p>}<details><summary>Ver confirmados ({participants.length}/24)</summary>{participants.length?<ul className="confirmed-list">{participants.map(p=><li key={p.id}>{p.display_name}</li>)}</ul>:<p className="muted">Ainda não há jogadores confirmados.</p>}</details></div></article>;
}

export function ScheduleEditor({session,save}:{session:Match;save:(s:Match,d:string,t:string)=>Promise<void>}){
 const [date,setDate]=useState(session.played_on),[time,setTime]=useState(session.starts_at?new Date(session.starts_at).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}):''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <details className="schedule-editor"><summary>{session.starts_at?'Alterar data e horário':'Definir data e horário'}</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await save(session,date,time);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}}><label>Data<input type="date" required value={date} onChange={e=>setDate(e.target.value)} disabled={busy}/></label><label>Início · Brasília<input type="time" required value={time} onChange={e=>setTime(e.target.value)} disabled={busy}/></label><p className="muted">Alterar o início também altera o prazo de cancelamento para todos os confirmados.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="secondary" disabled={busy}>Salvar horário</button></form></details>;
}
