'use client';

import {useCallback,useEffect,useRef,useState,type FormEvent,type CSSProperties} from 'react';
import {ArrowUpRight,Check,ChevronRight,ClipboardList,Goal,History,LogOut,Plus,RefreshCw,ShieldCheck,Shirt,Target,Trophy,Upload,Users,X} from 'lucide-react';
import {configured,friendlyError,getSupabase} from '@/lib/supabase';
import {currentDate,dateLabel,monthLabel,rankPlayers,validTotals,type Audit,type ClubData,type Match,type Performance,type Profile,type Ranked} from '@/lib/model';
import {demoData} from '@/lib/demo';

const EMPTY:ClubData={profiles:[],sessions:[],performances:[],slots:[],audit:[]};
type View='overview'|'ranking'|'matches'|'players'|'profile'|'admin';
type AuthMode='login'|'signup'|'forgot'|'recovery';
const POSITIONS=['GOL','DEF','MEI','ATA'] as const;

function Brand(){return <div className="brand"><span className="brand-icon">P/</span><span>PELADA<span className="brand-muted">CLUB</span></span></div>;}
function PlayerCard({player,month,large=false}:{player:Ranked;month:string;large?:boolean}){
 return <div className={`football-card ${large?'large':''}`} aria-label={`Cartinha de ${player.display_name}: ${player.points} pontos`}>
  <div className="card-inner"><div className="card-photo">{player.photo_url?<img src={player.photo_url} alt={`Foto de ${player.display_name}`} style={{objectPosition:`50% ${player.photo_y}%`}}/>:<div className="card-initials">{player.display_name.slice(0,2).toUpperCase()}</div>}<div className="card-rating"><strong>{player.points}</strong><span>PTS</span><span className="card-position">{player.position}</span></div><span className="card-edition">PC / CLUB</span></div>
  <div className="card-identity"><h3>{player.display_name}</h3><span>{monthLabel(month)}</span></div><div className="card-stats"><div><strong>{player.goals}</strong><span>GOLS</span></div><div><strong>{player.assists}</strong><span>ASSIST.</span></div><div><strong>{player.played}</strong><span>PELADAS</span></div></div></div>
 </div>;
}

function Auth({mode,setMode,onDemo}:{mode:AuthMode;setMode:(m:AuthMode)=>void;onDemo:()=>void}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();const sb=getSupabase();if(!sb)return;setBusy(true);setError('');setNotice('');try{
  if(mode==='login'){const {error}=await sb.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;}
  if(mode==='signup'){const {data,error}=await sb.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:location.origin+'/'}});if(error)throw error;if(!data.session)setNotice('Confira seu e-mail para confirmar o cadastro e depois entre com sua senha.');}
  if(mode==='forgot'){const {error}=await sb.auth.resetPasswordForEmail(email.trim(),{redirectTo:location.origin+'/?recover=1'});if(error)throw error;setNotice('Se esse e-mail estiver cadastrado, você receberá um link para criar uma nova senha.');}
  if(mode==='recovery'){const {error}=await sb.auth.updateUser({password});if(error)throw error;await sb.auth.signOut();history.replaceState(null,'','/');setMode('login');setNotice('Senha atualizada. Entre com a nova senha.');}
 }catch(err){setError(friendlyError(err));}finally{setBusy(false);}}
 return <main className="auth-page"><section className="auth-story"><Brand/><div><span className="eyebrow">O SEU FUTEBOL TEM HISTÓRIA.</span><h1>O próximo<br/>craque é<br/><em>da nossa turma.</em></h1><p>Uma cartinha para cada jogador.<br/>Cada gol e cada passe contam.</p></div><div className="auth-bottom"><span>24 POR PELADA</span><span>UMA PELADA. NOSSO CLUBE.</span></div></section><section className="auth-form-wrap"><div className="auth-form"><span className="eyebrow">VESTIÁRIO / PELADA CLUB</span><h2>{mode==='login'?'Bora pro jogo.':mode==='signup'?'Sua vaga no elenco.':mode==='forgot'?'Recupere seu acesso.':'Uma nova senha.'}</h2><p>{mode==='login'?'Entre para registrar seus números e ver o ranking.':mode==='signup'?'Use o e-mail que o organizador liberou para você.':mode==='forgot'?'Enviaremos um link para o seu e-mail.':'Escolha uma senha com pelo menos 8 caracteres.'}</p>
 {!configured&&<div className="notice">Estamos preparando o acesso da turma. Enquanto isso, você pode explorar a demonstração.</div>}
 <form onSubmit={submit}>{mode!=='recovery'&&<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required disabled={!configured||busy}/></label>}{mode!=='forgot'&&<label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={mode==='login'?1:8} autoComplete={mode==='login'?'current-password':'new-password'} required disabled={!configured||busy}/></label>}
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 <button className="primary full" disabled={!configured||busy}>{busy?'Aguarde…':mode==='login'?'Entrar no clube':mode==='signup'?'Criar minha conta':mode==='forgot'?'Enviar link':'Salvar nova senha'}<ArrowUpRight size={18}/></button></form>
 <div className="auth-links">{mode==='login'?<><button onClick={()=>{setMode('forgot');setError('');setNotice('');}}>Esqueci minha senha</button><button onClick={()=>{setMode('signup');setError('');setNotice('');}}>Primeiro acesso</button></>:<button onClick={()=>{setMode('login');setError('');setNotice('');}}>Voltar para entrar</button>}</div>
 {mode!=='recovery'&&<button className="secondary full demo-entry" onClick={onDemo}>Explorar demonstração <ChevronRight size={17}/></button>}<small>Gols e assistências registrados por quem joga.</small></div></section></main>;
}

export default function Club(){
 const [authMode,setAuthMode]=useState<AuthMode>('login'),[ready,setReady]=useState(false),[userId,setUserId]=useState<string|null>(null),[demo,setDemo]=useState(false),[demoRole,setDemoRole]=useState<'player'|'admin'>('player');
 const [data,setData]=useState<ClubData>(EMPTY),[view,setView]=useState<View>('overview'),[month,setMonth]=useState(currentDate().slice(0,7)),[sort,setSort]=useState<'points'|'goals'|'assists'>('points'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [selectedPlayer,setSelectedPlayer]=useState<string|null>(null),[editing,setEditing]=useState<{session:Match;player:Profile}|null>(null);
 const me=data.profiles.find(p=>p.id===(demo?'demo-0':userId));const isAdmin=demo?demoRole==='admin':me?.role==='admin';
 const ranked=rankPlayers(data,month,sort),ownRank=rankPlayers(data,month).find(p=>p.id===me?.id),star=rankPlayers(data,month)[0];
 const requestVersion=useRef(0);
 useEffect(()=>{const sb=getSupabase();if(!sb){setReady(true);return;}if(new URLSearchParams(location.search).get('recover')==='1')setAuthMode('recovery');const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('error_description'))setError('O link expirou ou não é válido. Solicite um novo link de recuperação.');let live=true;
  sb.auth.getSession().then(({data,error})=>{if(!live)return;if(error)setError(friendlyError(error));setUserId(data.session?.user.id??null);setReady(true);});
  const {data:{subscription}}=sb.auth.onAuthStateChange((event,session)=>{setUserId(session?.user.id??null);if(event==='PASSWORD_RECOVERY')setAuthMode('recovery');if(event==='SIGNED_OUT'){requestVersion.current++;setData(EMPTY);setView('overview');}});
  return()=>{live=false;subscription.unsubscribe();};
 },[]);
 useEffect(()=>{if(process.env.NODE_ENV==='production'&&'serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
 const load=useCallback(async(silent=false)=>{const sb=getSupabase();if(!sb||!userId||demo)return;const request=++requestVersion.current;if(!silent)setLoading(true);try{
  const results=await Promise.all([sb.from('profiles').select('*'),sb.from('sessions').select('*').order('played_on',{ascending:false}),sb.from('performances').select('*')]);for(const r of results)if(r.error)throw r.error;
  const profiles=(results[0].data??[]) as Profile[];const paths=profiles.map(p=>p.photo_path).filter((x):x is string=>Boolean(x));if(paths.length){const {data:urls,error}=await sb.storage.from('player-photos').createSignedUrls(paths,3600);if(error)throw error;profiles.forEach(p=>{p.photo_url=urls?.find(u=>u.path===p.photo_path)?.signedUrl??undefined;});}
  const admin=profiles.find(p=>p.id===userId)?.role==='admin';let slots:ClubData['slots']=[],audit:Audit[]=[];
  if(admin){const [s,a]=await Promise.all([sb.from('roster_slots').select('*').order('created_at'),sb.from('audit_log').select('*').order('created_at',{ascending:false}).limit(100)]);if(s.error)throw s.error;if(a.error)throw a.error;slots=s.data??[];audit=a.data??[];}
  if(request!==requestVersion.current)return;
  setData({profiles,sessions:results[1].data??[],performances:results[2].data??[],slots,audit});setError('');
 }catch(e){if(request===requestVersion.current)setError(friendlyError(e));}finally{if(request===requestVersion.current)setLoading(false);}},[userId,demo]);
 useEffect(()=>{void load();if(!userId||demo)return;const timer=setInterval(()=>{if(!document.hidden)void load(true);},30000);const focus=()=>void load(true);window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);requestVersion.current++;};},[load,userId,demo]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timer);},[notice]);
 function enterDemo(){requestVersion.current++;setDemo(true);setData(demoData());setDemoRole('player');setView('overview');setAuthMode('login');setError('');setMonth(currentDate().slice(0,7));setLoading(false);}
 async function logout(){if(demo){setDemo(false);setData(EMPTY);setView('overview');return;}const {error}=await getSupabase()!.auth.signOut();if(error)setError(friendlyError(error));}
 async function savePerformance(session:Match,player:Profile,goals:number,assists:number,previous:Performance|undefined){
  if(!validTotals(goals,assists))throw Error('invalid');
  if(!previous&&data.performances.filter(p=>p.session_id===session.id).length>=24)throw Error('24 participantes');
  if(demo){const id=previous?.id??crypto.randomUUID();const next:Performance={id,session_id:session.id,player_id:player.id,goals,assists,revision:(previous?.revision??0)+1,updated_at:new Date().toISOString()};setData(d=>({...d,performances:[...d.performances.filter(p=>p.id!==id),next],audit:[{id:Date.now(),actor_id:me!.id,performance_id:id,action:previous?'UPDATE':'INSERT',created_at:new Date().toISOString(),old_values:previous??null,new_values:next},...d.audit]}));}
  else{const sb=getSupabase()!;if(previous){const {data:rows,error}=await sb.from('performances').update({goals,assists}).eq('id',previous.id).eq('revision',previous.revision).select();if(error)throw error;if(!rows?.length)throw Error('conflict');}else{const {error}=await sb.from('performances').insert({session_id:session.id,player_id:player.id,goals,assists});if(error)throw error;}await load();}
  setNotice('Desempenho salvo. O ranking já foi atualizado.');
 }
 async function createMatch(name:string,date:string){if(demo){setData(d=>({...d,sessions:[{id:crypto.randomUUID(),name,played_on:date,status:'open',created_by:me!.id},...d.sessions]}));}else{const {error}=await getSupabase()!.from('sessions').insert({name,played_on:date,created_by:userId});if(error)throw error;await load();}setNotice('Pelada criada. A turma já pode registrar seus números na data do jogo.');}
 async function toggleMatch(match:Match){try{const status=match.status==='open'?'closed':'open';if(demo)setData(d=>({...d,sessions:d.sessions.map(s=>s.id===match.id?{...s,status}:s)}));else{const {data:changed,error}=await getSupabase()!.from('sessions').update({status}).eq('id',match.id).eq('status',match.status).select();if(error)throw error;if(!changed?.length){await load();throw Error('conflict');}await load();}setNotice(status==='closed'?'Pelada encerrada. Você ainda pode corrigir os registros.':'Pelada reaberta para registros.');}catch(e){setError(friendlyError(e));}}
 async function addSlot(name:string,email:string){if(demo){if(data.slots.some(s=>s.email.toLowerCase()===email.trim().toLowerCase()))throw {code:'23505'};setData(d=>({...d,slots:[...d.slots,{display_name:name,email,role:'player'}]}));}else{const {error}=await getSupabase()!.from('roster_slots').insert({display_name:name,email:email.trim().toLowerCase(),role:'player'});if(error)throw error;await load();}setNotice('E-mail liberado. O jogador já pode usar Primeiro acesso.');}
 async function saveProfile(profile:Profile,file:File|null){
  if(demo){const photo_url=file?await fileAsDataURL(file):profile.photo_url;setData(d=>({...d,profiles:d.profiles.map(p=>p.id===profile.id?{...profile,photo_url}:p)}));}
  else{const sb=getSupabase()!;let path=profile.photo_path;const oldPath=path;if(file){path=`${userId}/${crypto.randomUUID()}.webp`;const {error}=await sb.storage.from('player-photos').upload(path,file,{contentType:'image/webp',upsert:false});if(error)throw error;}
   const {data:updated,error}=await sb.from('profiles').update({display_name:profile.display_name,position:profile.position,photo_y:profile.photo_y,photo_path:path}).eq('id',userId).select();
   if(error||!updated?.length){if(file&&path)await sb.storage.from('player-photos').remove([path]);throw error??Error('profile');}if(file&&oldPath)await sb.storage.from('player-photos').remove([oldPath]);await load();}
  setNotice('Sua cartinha foi atualizada.');
 }
 if(!ready)return <main className="loading"><Brand/><p>Preparando o vestiário…</p></main>;
 if((!userId&&!demo)||authMode==='recovery')return <>{error&&<div className="global-error" role="alert">{error}<button aria-label="Fechar aviso" onClick={()=>setError('')}><X size={18}/></button></div>}<Auth mode={authMode} setMode={setAuthMode} onDemo={enterDemo}/></>;
 if(!me)return <main className="loading"><Brand/><h1>{loading?'Carregando sua turma…':'Não encontramos seu perfil.'}</h1><p>{error||'Confirme com o organizador se seu e-mail está liberado.'}</p><button className="primary" onClick={()=>load()}>Tentar novamente</button><button className="secondary" onClick={logout}>Sair</button></main>;
 const nav=[{id:'overview',label:'Visão geral',icon:Trophy},{id:'ranking',label:'Ranking',icon:ClipboardList},{id:'matches',label:'Peladas',icon:Goal},{id:'players',label:'Elenco',icon:Users},{id:'profile',label:'Minha carta',icon:Shirt},...(isAdmin?[{id:'admin',label:'Administração',icon:ShieldCheck}]:[])];
 const monthlyMatches=data.sessions.filter(s=>s.played_on.startsWith(month));
 return <div className="app-shell">
  {demo&&<div className="demo-bar"><span><strong>Demonstração</strong> · Dados fictícios; alterações duram nesta visita.</span><label>Testar como<select value={demoRole} onChange={e=>{setDemoRole(e.target.value as 'player'|'admin');setEditing(null);setView('overview');}}><option value="player">Jogador</option><option value="admin">Administrador</option></select></label></div>}
  <header className="app-header"><Brand/><div className="header-user"><span className="avatar">{me.display_name.slice(0,2).toUpperCase()}</span><span>{me.display_name}<small>{isAdmin?'Administrador':'Jogador'}</small></span><button className="icon-button" aria-label="Sair da conta" onClick={logout}><LogOut size={20}/></button></div></header>
  <div className="workspace"><aside className="sidebar"><nav aria-label="Navegação principal">{nav.map(({id,label,icon:Icon})=><button key={id} className={view===id?'active':''} aria-current={view===id?'page':undefined} onClick={()=>{setView(id as View);setSelectedPlayer(null);}}><Icon size={20}/>{label}{id==='players'&&<span className="nav-count">{data.profiles.length}</span>}</button>)}</nav><div className="sidebar-note"><span className="mini-mark">P/</span><p>O clube é nosso.<br/>A história também.</p><small>PELADA CLUB / 01</small></div></aside>
   <main className="main-content"><div className="page-top"><div><span className="eyebrow">{view==='admin'?'NA ORGANIZAÇÃO':view==='profile'?'SUA IDENTIDADE':'TEMPORADA DO CLUBE'}</span><h1>{view==='overview'?'Quem manda na resenha.':view==='ranking'?'O ranking da turma.':view==='matches'?'Dentro de campo.':view==='players'?'Nosso elenco.':view==='profile'?'Essa carta é sua.':'Tudo sob controle.'}</h1></div><label className="month-picker">Mês do ranking<input aria-label="Mês do ranking" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label></div>
   {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>load()}><RefreshCw size={16}/> Tentar novamente</button></div>}
   {notice&&<div className="toast" role="status"><Check size={18}/>{notice}<button aria-label="Fechar" onClick={()=>setNotice('')}><X size={16}/></button></div>}
   {view==='overview'&&<><div className="overview-grid"><section className="star-panel"><div className="section-kicker"><Trophy size={15}/>{(star?.points??50)>50?'CRAQUE DO MÊS':'A DISPUTA VAI COMEÇAR'}</div>{star&&<PlayerCard player={star} month={month} large/>}<div className="star-bottom"><span>{monthLabel(month)}</span><span>★ PELADA CLUB</span></div></section><section className="ranking-panel"><div className="section-heading"><h2>Na briga pelo topo</h2><span className="muted">{data.profiles.length} jogadores</span></div><div className="segmented" aria-label="Critério do ranking">{([{key:'points',label:'Geral'},{key:'goals',label:'Gols'},{key:'assists',label:'Assistências'}] as const).map(s=><button key={s.key} aria-pressed={sort===s.key} onClick={()=>setSort(s.key)}>{s.label}</button>)}</div><Ranking rows={ranked.slice(0,5)} me={me.id} onSelect={setSelectedPlayer}/><button className="text-button full-ranking-link" onClick={()=>setView('ranking')}>Ver ranking completo <ChevronRight size={16}/></button><p className="ranking-rule">Todos começam em <b>50</b>. Gol: <b>+3</b>. Assistência: <b>+2</b>.<br/>Limite de <b>100 pontos</b> por mês. A nota reinicia em 50 no próximo mês.<br/>Desempate por gols, depois assistências. Empates finais dividem a posição.</p></section></div>
    <section className="personal-strip"><div><span className="eyebrow">SEU MÊS EM CAMPO</span><h2>{(ownRank?.points??50)>50?`${ownRank!.rank}º no ranking`:'Seu primeiro lance começa aqui.'}</h2></div><div className="personal-numbers"><span><b>{ownRank?.goals??0}</b>gols</span><span><b>{ownRank?.assists??0}</b>assistências</span><span><b>{ownRank?.points??50}</b>pontos</span></div><button className="primary" onClick={()=>setView('matches')}>Registrar desempenho <ArrowUpRight size={18}/></button></section>
    <section className="section-space"><div className="section-heading"><h2>Peladas do mês</h2><button className="text-button" onClick={()=>setView('matches')}>Ver peladas <ChevronRight size={16}/></button></div>{monthlyMatches.length?monthlyMatches.slice(0,3).map(s=><MatchRow key={s.id} participantCount={data.performances.filter(p=>p.session_id===s.id).length} match={s} performance={data.performances.find(p=>p.session_id===s.id&&p.player_id===me.id)} onClick={()=>setEditing({session:s,player:me})} isAdmin={isAdmin}/>):<Empty title="Nenhuma pelada neste mês." text={isAdmin?'Crie uma pelada na Administração.':'O organizador vai adicionar os próximos jogos.'}/>}</section></>}
   {view==='ranking'&&<section className="ranking-panel complete-ranking" aria-label="Ranking completo do mês"><div className="section-heading"><div><h2>Classificação completa</h2><p className="muted">{monthLabel(month)} · {data.profiles.length} jogadores</p></div><span className="badge">Nota mensal · 50 a 100</span></div><div className="segmented" aria-label="Critério do ranking completo">{([{key:'points',label:'Geral'},{key:'goals',label:'Gols'},{key:'assists',label:'Assistências'}] as const).map(s=><button key={s.key} aria-pressed={sort===s.key} onClick={()=>setSort(s.key)}>{s.label}</button>)}</div><Ranking rows={ranked} me={me.id} onSelect={setSelectedPlayer}/><p className="ranking-rule">Todos começam em <b>50</b>. Gol: <b>+3</b>. Assistência: <b>+2</b>. Limite: <b>100</b>.<br/>Desempate por gols, depois assistências. Empates finais dividem a posição.<br/>Toque no nome de um jogador para ver sua cartinha.</p></section>}
   {view==='matches'&&<section><div className="section-heading"><div><h2>Seus gols. Seus passes.</h2><p className="muted">Informe o total da pelada, mesmo que seja zero. Cada jogo tem até 24 participantes. Salvar novamente substitui o total anterior.</p></div></div>{monthlyMatches.length?monthlyMatches.map(s=><MatchRow key={s.id} participantCount={data.performances.filter(p=>p.session_id===s.id).length} match={s} performance={data.performances.find(p=>p.session_id===s.id&&p.player_id===me.id)} onClick={()=>setEditing({session:s,player:me})} isAdmin={isAdmin}/>):<Empty title="Sem peladas neste mês" text="Selecione outro mês ou aguarde o organizador criar uma pelada."/>}</section>}
   {view==='players'&&<section><div className="section-heading"><h2>{data.profiles.length} jogadores, um clube.</h2><span className="muted">{monthLabel(month)}</span></div><div className="roster-grid">{rankPlayers(data,month).map(p=><button className="roster-card" key={p.id} onClick={()=>setSelectedPlayer(p.id)} aria-label={`Ver cartinha de ${p.display_name}`}><PlayerCard player={p} month={month}/><span className="roster-caption">{p.rank}º NO RANKING <ChevronRight size={14}/></span></button>)}</div></section>}
   {view==='profile'&&ownRank&&<ProfileEditor key={me.id} player={ownRank} month={month} save={saveProfile}/>}
   {view==='admin'&&isAdmin&&<Admin data={data} month={month} createMatch={createMatch} toggleMatch={toggleMatch} addSlot={addSlot} onEdit={(session,player)=>setEditing({session,player})}/>}
   <footer className="footer"><span>PELADA CLUB</span><span>{demo?'Demonstração interativa':'Gol · Assistência · Resenha'}</span><button className="text-button" disabled={loading||demo} onClick={()=>load()}><RefreshCw size={13}/>{loading?'Atualizando…':'Atualizar'}</button></footer>
   </main></div>
  {selectedPlayer&&<Modal title="Cartinha do jogador" onClose={()=>setSelectedPlayer(null)}><div className="player-modal"><PlayerCard player={rankPlayers(data,month).find(p=>p.id===selectedPlayer)!} month={month} large/><p>{monthLabel(month)} · Pontuação por gols e assistências</p></div></Modal>}
  {editing&&<PerformanceEditor session={editing.session} player={editing.player} previous={data.performances.find(p=>p.session_id===editing.session.id&&p.player_id===editing.player.id)} isAdmin={isAdmin} save={savePerformance} close={()=>setEditing(null)} onConflict={()=>load()}/>}
 </div>;
}

function Ranking({rows,me,onSelect}:{rows:Ranked[];me:string;onSelect:(id:string)=>void}){return <div className="table-wrap"><table className="ranking-table"><thead><tr><th>JOGADOR</th><th>G</th><th>A</th><th>PTS</th></tr></thead><tbody>{rows.map(p=><tr key={p.id} className={p.rank===1?'leader':''}><td><button onClick={()=>onSelect(p.id)}><span className="rank-number">{String(p.rank).padStart(2,'0')}</span><span>{p.display_name}{p.id===me&&<small className="you-label">você</small>}</span></button></td><td>{p.goals}</td><td>{p.assists}</td><td>{p.points}</td></tr>)}</tbody></table></div>;}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><Goal size={26}/><h3>{title}</h3><p>{text}</p></div>;}
function MatchRow({match,performance,onClick,isAdmin,participantCount}:{participantCount:number;match:Match;performance?:Performance;onClick:()=>void;isAdmin:boolean}){const full=!performance&&participantCount>=24;const available=!full&&(isAdmin||(match.status==='open'&&match.played_on<=currentDate()));return <div className="match-row"><div className="match-date"><strong>{match.played_on.slice(8)}</strong><span>{dateLabel(match.played_on).split(' ').slice(1).join(' ')}</span></div><div className="match-info"><h3>{match.name}</h3><span className={`status ${match.status}`}>{match.status==='closed'?'Encerrada':match.played_on>currentDate()?'Agendada':'Aberta para registros'}</span><span className="muted"> · {participantCount}/24 participantes</span></div><span className="match-totals">{performance?`${performance.goals} gols · ${performance.assists} assist.`:'Sem registro'}</span><button className="secondary" onClick={onClick} disabled={!available}>{available?(performance?'Editar total':'Registrar'):full?'Lotada':match.played_on>currentDate()?'Agendada':'Encerrada'}</button></div>;}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dlg=ref.current;dlg?.showModal();return()=>dlg?.close();},[]);return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Fechar janela" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;}
function PerformanceEditor({session,player,previous,isAdmin,save,close,onConflict}:{session:Match;player:Profile;previous?:Performance;isAdmin:boolean;save:(s:Match,p:Profile,g:number,a:number,prev?:Performance)=>Promise<void>;close:()=>void;onConflict:()=>void}){
 const [original]=useState(previous),[goals,setGoals]=useState(String(previous?.goals??0)),[assists,setAssists]=useState(String(previous?.assists??0)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();if(!goals.trim()||!assists.trim()||!validTotals(Number(goals),Number(assists)))return;setBusy(true);try{await save(session,player,Number(goals),Number(assists),original);close();}catch(err){if((err as Error).message==='conflict'){setError('Esse registro mudou em outra sessão. Feche esta janela e abra novamente para ver os valores atuais.');onConflict();}else setError(friendlyError(err));}finally{setBusy(false);}}
 return <Modal title={isAdmin?'Editar desempenho':'Meu desempenho'} onClose={()=>{if(!busy)close();}}><div className="edit-summary"><span>{dateLabel(session.played_on)} · {session.name}</span><h3>{player.display_name}</h3></div><form onSubmit={submit}><div className="score-inputs"><label><Target size={22}/>Gols<input aria-label="Total de gols" type="number" inputMode="numeric" min="0" max="99" step="1" required value={goals} disabled={busy} onChange={e=>setGoals(e.target.value)}/></label><label><Goal size={22}/>Assistências<input aria-label="Total de assistências" type="number" inputMode="numeric" min="0" max="99" step="1" required value={assists} disabled={busy} onChange={e=>setAssists(e.target.value)}/></label></div><p className="muted">Informe seus totais desta pelada. Os pontos entram direto no ranking.</p>{original&&<p className="muted">Anterior: {original.goals} gols e {original.assists} assistências.</p>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Salvando…':'Salvar desempenho'}<Check size={18}/></button></form></Modal>;
}

async function fileAsDataURL(file:File):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});}
async function preparePhoto(file:File):Promise<File>{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw Error('Escolha uma foto JPG, PNG ou WebP de até 5 MB.');
 const url=URL.createObjectURL(file);try{const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('Não foi possível abrir essa foto.'));image.src=url;});const scale=Math.min(1,1200/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Não foi possível preparar a foto.')),'image/webp',.88));return new File([blob],'photo.webp',{type:'image/webp'});}finally{URL.revokeObjectURL(url);}
}
function ProfileEditor({player,month,save}:{player:Ranked;month:string;save:(p:Profile,file:File|null)=>Promise<void>}){
 const [name,setName]=useState(player.display_name),[position,setPosition]=useState(player.position),[y,setY]=useState(player.photo_y),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(player.photo_url),[busy,setBusy]=useState(false),[preparing,setPreparing]=useState(false),[error,setError]=useState('');const tempUrl=useRef<string|null>(null);
 useEffect(()=>()=>{if(tempUrl.current)URL.revokeObjectURL(tempUrl.current);},[]);
 async function choose(file:File|undefined){if(!file)return;setPreparing(true);setError('');try{const normalized=await preparePhoto(file);if(tempUrl.current)URL.revokeObjectURL(tempUrl.current);tempUrl.current=URL.createObjectURL(normalized);setPhoto(normalized);setPreview(tempUrl.current);setY(25);}catch(e){setError((e as Error).message);}finally{setPreparing(false);}}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await save({...player,display_name:name.trim(),position,photo_y:y},photo);setPhoto(null);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 return <div className="profile-layout"><section className="profile-preview"><span className="eyebrow">SUA CARTINHA / {monthLabel(month)}</span><PlayerCard player={{...player,display_name:name,position,photo_y:y,photo_url:preview}} month={month} large/><p>O destaque é você.</p></section><form className="panel profile-form" onSubmit={submit}><h2>Do seu jeito.</h2><label>Nome na cartinha<input value={name} minLength={2} maxLength={32} required disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>Posição<select value={position} disabled={busy} onChange={e=>setPosition(e.target.value as Profile['position'])}>{POSITIONS.map(p=><option key={p}>{p}</option>)}</select></label><label className="upload-label"><Upload size={20}/> Foto do jogador<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||preparing} onChange={e=>choose(e.target.files?.[0])}/><small>JPG, PNG ou WebP · até 5 MB</small></label><label>Enquadramento vertical<input type="range" min="0" max="100" value={y} disabled={busy} onChange={e=>setY(Number(e.target.value))}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy||preparing||name.trim().length<2}>{preparing?'Preparando foto…':busy?'Salvando…':'Salvar minha carta'}<Check size={18}/></button></form></div>;
}

function Admin({data,month,createMatch,toggleMatch,addSlot,onEdit}:{data:ClubData;month:string;createMatch:(n:string,d:string)=>Promise<void>;toggleMatch:(s:Match)=>Promise<void>;addSlot:(n:string,e:string)=>Promise<void>;onEdit:(s:Match,p:Profile)=>void}){
 const [name,setName]=useState('Pelada de quinta'),[date,setDate]=useState(currentDate()),[email,setEmail]=useState(''),[playerName,setPlayerName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[section,setSection]=useState<'games'|'members'|'history'>('games'),[matchId,setMatchId]=useState(''),[playerId,setPlayerId]=useState('');
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 const matches=data.sessions.filter(s=>s.played_on.startsWith(month));const selected=matches.find(s=>s.id===matchId)??matches[0];const player=data.profiles.find(p=>p.id===playerId)??data.profiles[0];
 return <section><div className="segmented admin-tabs"><button aria-pressed={section==='games'} onClick={()=>setSection('games')}><ClipboardList size={16}/> Peladas</button><button aria-pressed={section==='members'} onClick={()=>setSection('members')}><Users size={16}/> Acessos</button><button aria-pressed={section==='history'} onClick={()=>setSection('history')}><History size={16}/> Histórico</button></div>{error&&<p className="error" role="alert">{error}</p>}
 {section==='games'&&<><form className="panel admin-create" onSubmit={e=>{e.preventDefault();action(()=>createMatch(name.trim(),date));}}><h2>Nova pelada</h2><div className="form-grid"><label>Nome<input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={80} required disabled={busy}/></label><label>Data<input type="date" required value={date} onChange={e=>setDate(e.target.value)} disabled={busy}/></label></div><button className="primary" disabled={busy||name.trim().length<2}><Plus size={18}/> Criar pelada</button></form>
 <div className="panel section-space"><h2>Corrigir um desempenho</h2><div className="form-grid"><label>Pelada<select value={selected?.id??''} onChange={e=>setMatchId(e.target.value)}>{!matches.length&&<option value="">Sem peladas no mês</option>}{matches.map(s=><option key={s.id} value={s.id}>{dateLabel(s.played_on)} · {s.name}</option>)}</select></label><label>Jogador<select value={player?.id??''} onChange={e=>setPlayerId(e.target.value)}>{data.profiles.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label></div><button className="secondary" disabled={!selected||!player||busy} onClick={()=>onEdit(selected,player)}>Editar gols e assistências</button></div>
 <div className="section-space"><h2>Controle das peladas</h2>{matches.map(s=><div className="admin-session" key={s.id}><div><strong>{s.name}</strong><p>{dateLabel(s.played_on)} · {s.status==='open'?'Aberta':'Encerrada'}</p></div><button className="secondary" disabled={busy} onClick={()=>action(()=>toggleMatch(s))}>{s.status==='open'?'Encerrar registros':'Reabrir registros'}</button></div>)}<p className="muted">Encerrar impede novas alterações pelos jogadores. Você continua podendo corrigir os números.</p></div></>}
 {section==='members'&&<><form className="panel" onSubmit={e=>{e.preventDefault();action(async()=>{await addSlot(playerName.trim(),email);setEmail('');setPlayerName('');});}}><div className="section-heading"><h2>Liberar acesso</h2><span className="badge">{data.slots.length} acessos liberados</span></div><p className="muted">Libere o e-mail de jogadores fixos e convidados. Todos criam a própria senha em Primeiro acesso e entram no ranking. Nenhum convite é enviado automaticamente.</p><div className="form-grid"><label>Nome<input value={playerName} onChange={e=>setPlayerName(e.target.value)} minLength={2} maxLength={32} required disabled={busy}/></label><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required disabled={busy}/></label></div><button className="primary" disabled={busy||playerName.trim().length<2}>Liberar jogador <Plus size={18}/></button></form><div className="section-space">{data.slots.map(s=><div className="member-row" key={s.email}><div><strong>{s.display_name}</strong><p>{s.email}</p></div><span className="badge">{s.role==='admin'?'Administrador':'Jogador'}</span></div>)}</div></>}
 {section==='history'&&<><h2>Últimas alterações</h2><p className="muted">Os 100 registros mais recentes, com autor e valores anteriores.</p>{!data.audit.length?<Empty title="Nenhuma alteração registrada" text="O histórico aparece assim que os desempenhos forem salvos."/>:data.audit.map(a=><div className="audit-row" key={a.id}><span className="audit-icon"><History size={18}/></span><div><strong>{data.profiles.find(p=>p.id===a.new_values.player_id)?.display_name??'Jogador'}</strong><p>{data.sessions.find(s=>s.id===a.new_values.session_id)?.name} · {a.old_values?`${a.old_values.goals} G / ${a.old_values.assists} A → `:''}{a.new_values.goals} G / {a.new_values.assists} A</p><small>Por {data.profiles.find(p=>p.id===a.actor_id)?.display_name??'Organização'} · {new Date(a.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></div></div>)}</>}
 </section>;
}
